// Comprehensive Mock Data for ApexCMS Admin Panel

export const INITIAL_STATS = {
  activeJobs: 12,
  totalJobs: 28,
  publishedBlogs: 45,
  draftBlogs: 7,
  unreadEnquiries: 14,
  totalEnquiries: 382,
  publishingStatus: 'Synced', // 'Synced', 'Changes Pending', 'Deploying', 'Error'
  lastPublishedAt: '2026-10-06 10:15 AM',
  lastPublishedBy: 'Sarah Jenkins (Lead Editor)',
  pendingPublishCount: 3,
};

export const INITIAL_JOBS = [
  {
    id: 'JOB-101',
    title: 'Senior Full Stack Engineer (React & Node.js)',
    department: 'Engineering',
    location: 'San Francisco, CA (Hybrid)',
    type: 'Full-time',
    experience: 'Senior (5+ yrs)',
    salary: '$165,000 - $195,000',
    status: 'Active',
    applicantsCount: 42,
    publishedAt: '2026-09-28',
    description: 'We are seeking a Senior Full Stack Engineer to lead front-end architecture and API development for our core SaaS offerings. You will collaborate closely with product designers and platform engineers.',
    requirements: '5+ years experience with React, Node.js, TypeScript, PostgreSQL. Strong UI/UX principles and experience with CI/CD deployment pipelines.',
  },
  {
    id: 'JOB-102',
    title: 'Lead Product Designer (Design Systems)',
    department: 'Design',
    location: 'Remote (US/Canada)',
    type: 'Full-time',
    experience: 'Lead / Principal',
    salary: '$150,000 - $180,000',
    status: 'Active',
    applicantsCount: 29,
    publishedAt: '2026-09-30',
    description: 'Join our design team to build and scale our enterprise design system across desktop and web platforms. You will establish visual guidelines, interaction design standards, and component specs.',
    requirements: 'Figma mastery, HTML/CSS knowledge, minimum 4 years leading design system initiatives in B2B SaaS companies.',
  },
  {
    id: 'JOB-103',
    title: 'DevOps & Cloud Infrastructure Architect',
    department: 'Infrastructure',
    location: 'Austin, TX',
    type: 'Full-time',
    experience: 'Senior (6+ yrs)',
    salary: '$170,000 - $205,000',
    status: 'Active',
    applicantsCount: 18,
    publishedAt: '2026-10-01',
    description: 'Responsible for maintaining Kubernetes clusters, multi-region AWS deployments, zero-downtime releases, and automated security compliance scanning.',
    requirements: 'AWS Solutions Architect certified, Terraform, Docker, Kubernetes, Prometheus, Datadog.',
  },
  {
    id: 'JOB-104',
    title: 'Content Marketing Specialist & Technical Writer',
    department: 'Marketing',
    location: 'New York, NY (Hybrid)',
    type: 'Full-time',
    experience: 'Mid-Level (3+ yrs)',
    salary: '$95,000 - $115,000',
    status: 'Draft',
    applicantsCount: 0,
    publishedAt: '2026-10-04',
    description: 'Craft compelling developer documentation, blog posts, whitepapers, and customer case studies detailing enterprise cloud migrations.',
    requirements: 'Superb written English, experience writing technical blogs or developer documentation, SEO best practices.',
  },
  {
    id: 'JOB-105',
    title: 'Enterprise Account Executive',
    department: 'Sales',
    location: 'Remote (US)',
    type: 'Full-time',
    experience: 'Senior (4+ yrs)',
    salary: '$130,000 + Uncapped OTE',
    status: 'Active',
    applicantsCount: 35,
    publishedAt: '2026-09-15',
    description: 'Drive new revenue acquisition across Fortune 500 accounts. Manage full sales cycles from initial discovery to closing multivariable enterprise contracts.',
    requirements: 'Proven track record exceeding $1.5M ARR quota in B2B SaaS, Salesforce expertise.',
  },
  {
    id: 'JOB-106',
    title: 'Customer Success Manager (APAC Region)',
    department: 'Customer Operations',
    location: 'Singapore (Remote)',
    type: 'Full-time',
    experience: 'Mid-Level',
    salary: '$85,000 - $105,000',
    status: 'Closed',
    applicantsCount: 64,
    publishedAt: '2026-08-10',
    description: 'Own account health, renewal metrics, and adoption strategy for key accounts across Asia-Pacific.',
    requirements: 'Fluent in English and Mandarin. 3+ years in B2B Account Management or CSM roles.',
  },
  {
    id: 'JOB-107',
    title: 'Junior QA & Automation Test Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'Full-time',
    experience: 'Entry / Junior',
    salary: '$80,000 - $95,000',
    status: 'Closed',
    applicantsCount: 88,
    publishedAt: '2026-08-01',
    description: 'Build end-to-end Cypress and Playwright tests for web applications and REST API suites.',
    requirements: 'Bachelor in CS or equivalent, basic JS/TypeScript script writing experience.',
  }
];

export const INITIAL_APPLICANTS = [
  {
    id: 'APP-501',
    jobId: 'JOB-101',
    jobTitle: 'Senior Full Stack Engineer (React & Node.js)',
    name: 'Michael Vance',
    email: 'michael.vance@example.com',
    phone: '+1 (555) 382-9102',
    experience: '6 Years',
    submittedAt: '2026-10-05 2:40 PM',
    status: 'In Review',
    notes: 'Strong portfolio with open-source React contributions. Recommended for technical interview.',
    resumeUrl: '#',
  },
  {
    id: 'APP-502',
    jobId: 'JOB-101',
    jobTitle: 'Senior Full Stack Engineer (React & Node.js)',
    name: 'Elena Rostova',
    email: 'elena.rostova@techmail.org',
    phone: '+1 (555) 741-2098',
    experience: '8 Years',
    submittedAt: '2026-10-04 11:15 AM',
    status: 'Shortlisted',
    notes: 'Ex-Stripe engineer. Deep knowledge of microservices and GraphQL architecture.',
    resumeUrl: '#',
  },
  {
    id: 'APP-503',
    jobId: 'JOB-102',
    jobTitle: 'Lead Product Designer (Design Systems)',
    name: 'David Kim',
    email: 'david.kim@designworks.io',
    phone: '+1 (555) 902-1144',
    experience: '5 Years',
    submittedAt: '2026-10-05 09:30 AM',
    status: 'New',
    notes: 'Submitted impressive Figma design tokens showcase.',
    resumeUrl: '#',
  }
];

export const INITIAL_BLOGS = [
  {
    id: 'BLOG-201',
    title: 'Architecting Scalable SaaS Micro-Frontends with React & Vite',
    slug: 'architecting-scalable-saas-micro-frontends-react-vite',
    category: 'Engineering',
    author: 'Alex Rivera (VP of Engineering)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    status: 'Published',
    views: '4,290',
    readTime: '6 min read',
    publishedAt: '2026-10-02',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    excerpt: 'Discover how modern modular front-end architectures reduce build bottlenecks and streamline cross-team releases in high-velocity tech teams.',
    content: `<h2>The Challenge of Monolithic Front-Ends</h2><p>As enterprise web applications scale, single front-end repositories frequently turn into development bottlenecks. Long build times, coupled release cycles, and merge conflicts degrade developer productivity.</p><h3>Implementing Module Federation with Vite</h3><p>By splitting core modules like <strong>Billing</strong>, <strong>Analytics</strong>, and <strong>User Management</strong> into independently deployed micro-frontends, organizations can empower domain teams to ship software autonomously.</p><ul><li>Independent build targets</li><li>Shared UI design tokens</li><li>Zero-downtime blue/green deployment strategy</li></ul>`,
    seoTitle: 'Scalable Micro-Frontends with React & Vite | ApexCorp Tech Blog',
    seoDescription: 'Learn how to architect high-performance SaaS applications with modular micro-frontends using React, Vite, and module federation.',
  },
  {
    id: 'BLOG-202',
    title: 'Building Enterprise Design Systems: From Tokens to Accessibility',
    slug: 'building-enterprise-design-systems-tokens-accessibility',
    category: 'Design',
    author: 'Jessica Chen (Head of UX)',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    status: 'Published',
    views: '2,810',
    readTime: '8 min read',
    publishedAt: '2026-09-25',
    coverImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    excerpt: 'An actionable blueprint on structuring color palettes, typography scales, ARIA standards, and component contracts for enterprise software.',
    content: `<h2>Establishing Design Token Standardization</h2><p>Design tokens act as the atomic source of truth bridging Figma design files and production CSS variables.</p><h3>Ensuring WCAG 2.1 AA Compliance</h3><p>Every interactive component must satisfy high contrast ratios, screen reader announcements, and keyboard navigation focus states.</p>`,
    seoTitle: 'Enterprise Design Systems & Accessibility Guide | ApexCorp',
    seoDescription: 'Complete roadmap to building scalable, WCAG AA compliant design systems for enterprise software apps.',
  },
  {
    id: 'BLOG-203',
    title: 'Q3 2026 Product Update: AI-Assisted Workflow Automation',
    slug: 'q3-2026-product-update-ai-assisted-workflow-automation',
    category: 'Product',
    author: 'Marcus Vance (Product Director)',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    status: 'Published',
    views: '6,140',
    readTime: '4 min read',
    publishedAt: '2026-09-18',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    excerpt: 'Announcing automated workflow triggers, multi-channel approval queues, and enhanced audit trails across the entire Apex platform.',
    content: `<h2>Streamlining Operations with Intelligent Triggers</h2><p>We are thrilled to roll out our most requested features for Q3, including smart workflow routing and automated data sync.</p>`,
    seoTitle: 'Apex Q3 2026 Product Release & Features | ApexCorp',
    seoDescription: 'Explore the new AI workflow triggers and enterprise security capabilities launched in Q3 2026.',
  },
  {
    id: 'BLOG-204',
    title: 'Zero-Trust Cloud Security Architecture for Modern B2B SaaS',
    slug: 'zero-trust-cloud-security-architecture-b2b-saas',
    category: 'Company',
    author: 'David Sterling (Chief Security Officer)',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    status: 'Draft',
    views: '0',
    readTime: '10 min read',
    publishedAt: 'Unpublished',
    coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
    excerpt: 'Why traditional perimeter defenses fail in multi-cloud environments and how continuous authorization safeguards sensitive customer data.',
    content: `<h2>Principles of Zero-Trust Network Access</h2><p>Never trust, always verify. Every API request must be authenticated, authorized, and encrypted in transit.</p>`,
    seoTitle: 'Zero-Trust Security Architecture for Cloud SaaS',
    seoDescription: 'In-depth guide to SOC2 Type II compliance, continuous API token verification, and data encryption standards.',
  },
  {
    id: 'BLOG-205',
    title: 'How Global Logistics Leader Reduced API Latency by 65%',
    slug: 'how-global-logistics-leader-reduced-api-latency-by-65',
    category: 'Case Studies',
    author: 'Sarah Jenkins (Lead Editor)',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    status: 'Scheduled',
    views: '0',
    readTime: '5 min read',
    publishedAt: '2026-10-12 (Scheduled)',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    excerpt: 'Case study demonstrating how real-time edge caching and database indexing accelerated supply chain tracking requests.',
    content: `<h2>Customer Spotlight: TransGlobal Freight</h2><p>TransGlobal Freight handles over 10 million tracking queries daily across 40 countries...</p>`,
    seoTitle: 'TransGlobal Freight Case Study | Latency Reduction',
    seoDescription: 'See how TransGlobal Freight optimized high-concurrency API performance with Apex platform infrastructure.',
  }
];

export const BLOG_CATEGORIES = ['Engineering', 'Design', 'Product', 'Company', 'Case Studies'];

export const INITIAL_ENQUIRIES = [
  {
    id: 'ENQ-301',
    senderName: 'Robert Langdon',
    email: 'robert.langdon@acme-corp.com',
    company: 'Acme Corporation (Global Tech)',
    phone: '+1 (415) 892-0192',
    category: 'Sales / Enterprise Inquiry',
    subject: 'Request for custom enterprise pricing & SOC2 compliance documentation',
    message: 'Hello Team,\n\nWe are evaluating CMS and web administrative platforms for our multi-brand digital transformation across 15 global markets. We would like to request an intro demo with your enterprise solution architects and review your SOC2 Type II compliance audit reports.\n\nCould we schedule a call this Thursday at 2:00 PM EST?\n\nBest regards,\nRobert Langdon\nVP of Digital Infrastructure, Acme Corp',
    receivedAt: '2026-10-06 09:42 AM',
    status: 'Unread', // 'Unread', 'Read', 'Replied', 'Archived'
    isStarred: true,
    history: [
      { type: 'received', timestamp: '2026-10-06 09:42 AM', text: 'Enquiry received via Website Contact Form.' }
    ]
  },
  {
    id: 'ENQ-302',
    senderName: 'Dr. Amanda Lewis',
    email: 'alewis@biomedlabs.org',
    company: 'BioMed Research Labs',
    phone: '+1 (617) 402-8811',
    category: 'Careers / General Inquiry',
    subject: 'Inquiry regarding Senior Full Stack Engineer opening (JOB-101)',
    message: 'Dear Hiring Manager,\n\nI am writing to inquire if the Senior Full Stack position is open to fully remote candidates located on the East Coast of the US, or if onsite presence in SF is strictly required.\n\nI have over 7 years of React and PostgreSQL experience in regulated healthtech environments.\n\nThank you,\nDr. Amanda Lewis',
    receivedAt: '2026-10-05 04:15 PM',
    status: 'Unread',
    isStarred: false,
    history: [
      { type: 'received', timestamp: '2026-10-05 04:15 PM', text: 'Enquiry received via Careers Page Form.' }
    ]
  },
  {
    id: 'ENQ-303',
    senderName: 'Carlos Gomez',
    email: 'cgomez@fintech-innovations.io',
    company: 'Fintech Innovations Inc',
    phone: '+1 (305) 554-9920',
    category: 'Partnerships',
    subject: 'Strategic integration partnership proposal for Apex CMS',
    message: 'Hi Apex Team,\n\nOur team builds automated content translation APIs for financial institutions. We would love to discuss a native integration module for Apex CMS users.',
    receivedAt: '2026-10-04 11:30 AM',
    status: 'Replied',
    isStarred: true,
    history: [
      { type: 'received', timestamp: '2026-10-04 11:30 AM', text: 'Enquiry received via Partner Contact Portal.' },
      { type: 'replied', timestamp: '2026-10-04 02:10 PM', text: 'Replied by Sarah Jenkins: Sent Partner Integration Kit and scheduled follow-up call.' }
    ]
  },
  {
    id: 'ENQ-304',
    senderName: 'Sophie Bennett',
    email: 'sophie.bennett@mediawave.co.uk',
    company: 'MediaWave Digital UK',
    phone: '+44 20 7946 0912',
    category: 'Media / Press',
    subject: 'Press inquiry regarding Q3 product announcements',
    message: 'Hi there,\n\nI am drafting an article for TechRadar UK regarding enterprise CMS updates in 2026. Would someone from leadership be available for a 15-min interview?',
    receivedAt: '2026-10-03 01:20 PM',
    status: 'Read',
    isStarred: false,
    history: [
      { type: 'received', timestamp: '2026-10-03 01:20 PM', text: 'Enquiry received via Press Contact Form.' }
    ]
  },
  {
    id: 'ENQ-305',
    senderName: 'Jonathan Hayes',
    email: 'jhayes@apex-customer.com',
    company: 'Hayes Logistics',
    phone: '+1 (206) 881-2300',
    category: 'Technical Support',
    subject: 'Sitemap indexing question for multi-language blog domain',
    message: 'Can someone clarify how the automatic XML sitemap generator handles localized hreflang tags for sub-domains?',
    receivedAt: '2026-10-01 10:05 AM',
    status: 'Archived',
    isStarred: false,
    history: [
      { type: 'received', timestamp: '2026-10-01 10:05 AM', text: 'Enquiry received via Support Desk.' }
    ]
  }
];

export const INITIAL_PUBLISHING_LOGS = [
  {
    id: 'PUB-901',
    event: 'Published Website Sync (Production)',
    author: 'Sarah Jenkins',
    changes: 'Updated 2 Blog posts, 1 Job Opening',
    timestamp: '2026-10-06 10:15 AM',
    status: 'Success',
    commitHash: '7f3a9d2',
  },
  {
    id: 'PUB-902',
    event: 'Staging Environment Preview',
    author: 'Alex Rivera',
    changes: 'Modified Hero headline & Careers page header',
    timestamp: '2026-10-05 05:40 PM',
    status: 'Success',
    commitHash: '2b91e01',
  },
  {
    id: 'PUB-903',
    event: 'Published Website Sync (Production)',
    author: 'Marcus Vance',
    changes: 'Published BLOG-201 and JOB-101',
    timestamp: '2026-10-02 09:00 AM',
    status: 'Success',
    commitHash: '8e44c12',
  }
];

export const SYSTEM_USERS = [
  {
    id: 'USR-01',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@apexcorp.com',
    role: 'Super Admin / Lead Editor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: 'Just now',
  },
  {
    id: 'USR-02',
    name: 'Alex Rivera',
    email: 'alex.rivera@apexcorp.com',
    role: 'Engineering Director',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '25 min ago',
  },
  {
    id: 'USR-03',
    name: 'Jessica Chen',
    email: 'jessica.chen@apexcorp.com',
    role: 'Head of UX & Content',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '2 hours ago',
  },
  {
    id: 'USR-04',
    name: 'Marcus Vance',
    email: 'marcus.vance@apexcorp.com',
    role: 'Product Content Lead',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    status: 'Offline',
    lastActive: 'Yesterday at 4:30 PM',
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-1',
    title: 'New High Priority Enquiry',
    message: 'Robert Langdon (Acme Corp) submitted an enterprise sales inquiry.',
    time: '12 min ago',
    read: false,
    type: 'enquiry',
  },
  {
    id: 'NOTIF-2',
    title: 'Applicant Milestone Reached',
    message: 'JOB-101 (Senior Full Stack Engineer) reached 40+ candidate applications.',
    time: '2 hours ago',
    read: false,
    type: 'career',
  },
  {
    id: 'NOTIF-3',
    title: 'Content Deployment Succeeded',
    message: 'Production build #7f3a9d2 deployed successfully to global CDN.',
    time: '3 hours ago',
    read: true,
    type: 'system',
  },
  {
    id: 'NOTIF-4',
    title: 'Scheduled Blog Reminder',
    message: 'BLOG-205 (TransGlobal Freight Case Study) is scheduled for Oct 12.',
    time: '1 day ago',
    read: true,
    type: 'blog',
  }
];

export const ACTIVITY_LOG = [
  {
    id: 'ACT-1',
    user: 'Sarah Jenkins',
    action: 'published article',
    target: 'Architecting Scalable SaaS Micro-Frontends',
    time: '2 hours ago',
  },
  {
    id: 'ACT-2',
    user: 'Alex Rivera',
    action: 'created new job opening',
    target: 'Senior Full Stack Engineer (JOB-101)',
    time: '4 hours ago',
  },
  {
    id: 'ACT-3',
    user: 'Sarah Jenkins',
    action: 'replied to enquiry',
    target: 'ENQ-303 (Fintech Innovations Inc)',
    time: '1 day ago',
  },
  {
    id: 'ACT-4',
    user: 'Marcus Vance',
    action: 'updated website settings',
    target: 'Global SEO Title Tag & Sitemap XML',
    time: '2 days ago',
  }
];
